---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Render Readme"

on:
  workflow_call:

jobs:
  render-readme:
    name: Render README
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version: 3.x
          cache: pip

      - name: Install Python Requirements
        shell: bash
        run: pip install --requirement requirements.txt && pip freeze

      - name: Render README
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        shell: bash
        run: python ./scripts/render-readme.py

      - name: Commit Changes
        uses: planetscale/ghcommit-action@c6125dee9e9c0daebc4adea9f68ead8293414174 # v0.2.9
        with:
          commit_message: "chore: regenerate README.md [skip ci]"
          repo: ${{ github.repository }}
          branch: main
          empty: false
          file_pattern: "README.md"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
